[global_tags]

[agent]
debug = true
interval = "3s"


[[controllers.http]]
address = ":9999"    # 默认端口9999


[[outputs.redis]]
url_address = "redis://localhost:6379/0"
output_channel = "output_test"


[[inputs.fake]]
name_override = "fake_tengqing_opc"
interval = "2s"
point_map = "../configs/point_map_opc.yml"