#title = "Deivce Adaptor Configuration"

[global_tags]
test = "test"

[agent]
debug = true
interval = "3s"

[[controllers.http]]
address = ":9999"

[[outputs.redis]]
#[outputs.file]
#files = ["stdout"]
#data_format = "json"

[[inputs.modbus]]
name_override = "abc"
field_prefix = "abc_"
field_suffix = ""
interval = "1s"
address = "10.211.55.4:5021"
slave_id = 1
point_map = "../configs/point_map_modbus.yml"


[[inputs.modbus]]
interval = "1s"
address = "10.211.55.4:502"
slave_id = 1
point_map = "../configs/point_map_modbus.yml"


#[[inputs.ftp]]
#address = "localhost"
#username = "leaniot"
#password = "leaniot"
#dev_path = "/SubFile/KJ95N/dev.txt"
#data_path = "/SubFile/KJ95N/rtdata.txt"

[[inputs.sensor_vibration]]
name_override = "vibration_sensor"

[[inputs.sensor_vibration.parser.a]]
[[inputs.sensor_vibration.parser.b]]
[[inputs.sensor_vibration.parser.c]]


[[inputs.http_listener]]

[[inputs.http_listener.parser.data]]
parser = "csv"
other = 2
[[inputs.http_listener.parser.dev]]
parser = "vibration"
other = 1

#map[parser:[0xc0001f49b0]]



#[inputs.s7]
#interval = "1s"
#address = "192.168.0.168"
#rack = 0
#slot = 1
#point_map = "../configs/point_map_s7.yml"