
[agent]
  collection_jitter = "10ms"
  debug = true
  flush_interval = "10s"
  flush_jitter = "10ms"
  interval = "3s"

[controllers]

  [[controllers.http]]
    address = ":9999"

[inputs]

  [[inputs.fake]]
    interval = "3s"
    name_override = "fake_tengqing_opc"
    point_map = "../configs/point_map_opc.yml"

  [[inputs.http_listener]]
    interval = "3s"
    name_override = ""
    point_map = ""

    [inputs.http_listener.parser]

      [[inputs.http_listener.parser.data]]
        other = 2.0
        parser_name = "csv"

      [[inputs.http_listener.parser.dev]]
        other = 1.0
        parser_name = "vibration"

  [[inputs.modbus]]
    address = "10.211.55.4:502"
    interval = "3s"
    point_map = "../configs/point_map_modbus.yml"

[outputs]

  [[outputs.redis]]
    data_format = "json"
    output_channel = "output_test"
    url_address = "redis://localhost:6379/0"
