
[agent]
  collection_jitter = "10ms"
  debug = true
  flush_interval = "10s"
  flush_jitter = "10ms"
  interval = "3s"

[controllers]

  [[controllers.http]]
    address = ":9999"

[inputs]

  [[inputs.fake]]
    interval = "3s"
    name_override = "fake"
    point_map = ""

  [[inputs.fake]]
    interval = "3s"
    name_override = "fake"
    point_map = ""

[outputs]

  [[outputs.redis]]
    data_format = "json"
    url_address = "redis://localhost:6379/0"
